services:
  - type: web
    name: microimport-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://admin:mizou450@cluster0.xb4dzcy.mongodb.net/Import?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://importf.onrender.com
      - key: CLIENT_URL
        value: https://importf.onrender.com
